server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost/simple
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop